# Generated by Django 6.0.5 on 2026-06-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('bed_time', models.TimeField(blank=True, null=True)),
                ('total_sleep', models.FloatField(default=0)),
                ('yoga', models.PositiveIntegerField(default=0)),
                ('meditation', models.PositiveIntegerField(default=0)),
                ('gym', models.PositiveIntegerField(default=0)),
                ('play', models.PositiveIntegerField(default=0)),
                ('semester_study', models.FloatField(default=0)),
                ('project', models.FloatField(default=0)),
                ('leetcode', models.FloatField(default=0)),
                ('self_study', models.FloatField(default=0)),
                ('mobile', models.FloatField(default=0)),
                ('expense', models.FloatField(default=0)),
                ('water', models.FloatField(default=0)),
                ('oil', models.PositiveIntegerField(default=0)),
                ('bath', models.PositiveIntegerField(default=0)),
                ('kayakalpam', models.PositiveIntegerField(default=0)),
                ('protein', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('fruits', models.BooleanField(default=False)),
                ('amla_juice', models.BooleanField(default=False)),
                ('sabja_badam', models.BooleanField(default=False)),
                ('maida', models.BooleanField(default=False)),
                ('white_sugar', models.BooleanField(default=False)),
                ('career_video', models.PositiveIntegerField(default=0)),
                ('health_video', models.PositiveIntegerField(default=0)),
                ('newspaper', models.PositiveIntegerField(default=0)),
                ('typewriting', models.PositiveIntegerField(default=0)),
                ('sleep_score', models.FloatField(default=0)),
                ('exercise_score', models.FloatField(default=0)),
                ('study_score', models.FloatField(default=0)),
                ('nutrition_score', models.FloatField(default=0)),
                ('health_score', models.FloatField(default=0)),
                ('lifestyle_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
